FROM node:24-alpine


WORKDIR /app

# Copy package files first to leverage Docker cache
COPY package*.json ./

# Install all dependencies (including devDeps for types)
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the port
EXPOSE 3000

# Default command (overridden by docker-compose for dev)
CMD ["npm", "run", "dev"]